### ISSUE TITLE
Cron, php switcher, and other comments...

### ISSUE THREAD

**Issue by hostquota** [AlternC/easy-install#10]

**Comment by hostquota** [comment]
I am really impressed with alternc and have been checking it out all over Google! It's certainly a good panel, and I've tested dozens. Was wondering if there were any plans to include a cron scheduler, and php switcher? These would make great additions to alternc. Also, is there a sample module, one which could be used to create plug-ins?
It's a brilliant project and I understand things take time, I will certainly make my own contributions once I've figured it all out!
Thanks everyone who's put this together!

**Comment by drousseau** [comment]
Hi hostquota,
Your questions are "larger" than easy-install which is only a helper script for bootstraping an AlternC instance and may better fit the "AlternC" github project.

There is some sort of "cron" scheduler, where each panel user can set up some recuring tasks. You can only define the periodicity (every X hours), not precisely "at 4pm", but it fits for most of the needs.

For the "php switcher", not much is built-in, but you can easily define (through database entries) you own "virtualhost types", and setup multiple web fontends with different PHP settings (at Neuronnexion we use it to provide different PHP versions).

You can also look the "alternc-mailman" github project which is a separately-maintained module.

**Comment by hostquota** [comment]
Thanks Drousseau, ok I'm going to doare-install and see how I get on. Thanks again, love the project!

**Comment by camlafit** [comment]
Hi

I close this issue is not related to easy-install as said by @drousseau . Then I close this issue. 
You're invited to reopen these issue on https://github.com/AlternC/AlternC/issues 

Thanks a lot with your help.
