### ISSUE TITLE
cgi-bin

### ISSUE THREAD

**Issue by hostquota** [AlternC/easy-install#11]
I need to run a perl script from cgi-bin but can't find it in filemanager. I know it exists, but where? Also, can cgi-bin be enabled for all users?

**Comment by camlafit** [comment]
Can you open this issue on https://github.com/AlternC/AlternC ?
Is not related to easy-install feature.

Thanks

**Comment by hostquota** [comment]
Ok Camlafit, seeing as you like to be so ignorant and rude to others: Mailman doesn't work via easy install, cannot log in, no such user. There is no cron via easy install, unless you go to cron.php in your browser, then click the button, then restart. Had to find that out myself because easy install is not so easy after all.
You cannot add certificates via easy install because there is no link for it in admin, unlike in your demo. Your filemanager is useless, it cannot unzip, you can't upload more than 2M unless you alter php.ini yourself, I had to install net2ftp, a far better way of doing things. 
All in all, seeing as you only like answering questions about easy install.....easy install is a waste of time. How about some proper instructions...I mean 11 years later, I'd have thought you could have at least got that right.
In fiuture, if you want politeness, give politeness, it's people like you who give the French a bad name. As far as I'm concerned, I liked Alternc before I heard of YOU. Now I'll never touch it again you ignorant B.
