### ISSUE TITLE
Debian Strech installation fail: alternc-mailman doesn't exist

### ISSUE THREAD

**Issue by greencopper** [AlternC/easy-install#16]
I just tried the installation script on Debian Stretch. During the installation the script failes because it cannot install `alternc-mailman`

```
# aptitude search alternc
alternc
alternc-admintools
alternc-api
alternc-awstats
alternc-roundcube
alternc-slave
alternc-squirrelmail
alternc-ssl
alternc-upnp
alternc-webmail
```

No mailman.

**Comment by greencopper** [comment]
I manually installed the packages I needed in order to test, but I give up, so many errors during usage that I can't even report them here.

**Comment by camlafit** [comment]
Hello

About mailmain it's actually broken. Only nightly version should be ok.
After last AlternC camp we must release all theses packages but we have
leak some time to do it :/

Nightly are actually stable, and I think it's better to try with these.
Could you edit your config.sh file and set ```NIGHTLY = 1 ``` ?

Thanks
