### ISSUE TITLE
arm64 repository error

### ISSUE THREAD

**Issue by erdoukki** [AlternC/easy-install#17]
`N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'http://debian.alternc.org stretch InRelease' doesn't support architecture 'arm64'`

is there any planned portage to arm64 ?

**Comment by camlafit** [comment]
Hello

Actually we have not any plan about arm64.
Could be interessting if somebody try to compile package from source and open issues related.

**Comment by erdoukki** [comment]
Thanks for the proposal...
I just give a check and all debian package compile without error...on a debian stretch chroot on an EspressoBin Board.

I cannot go further in my tests because I am in a chroot from OpenWRT and the acl support is not implemented in the kernel used, so the main package stop installation with a message about acl support needed !

**Comment by camlafit** [comment]
Hello

I you want you can open an issue on Alternc/Alternc project. Here is only
related about an easy install helper script.
As we don't have arm environnement we can't actully compile to this arch
but in future maybe we can do add it.

Thanks
