### ISSUE TITLE
MySQL server and client are no longer available by default on debian

### ISSUE THREAD

**Issue by rsmithlal** [AlternC/easy-install#18]
Hi folks,

I'm running into an issue running the easy install on Debian 12.

```bash
apt-get install -y mysql-server mysql-client
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package mysql-server is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package mysql-client is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'mysql-server' has no installation candidate
E: Package 'mysql-client' has no installation candidate


A critical error occured: Failed to following package(s): [ mysql-server mysql-client ]
Exiting.
```

I've seen guides refer to needing to download and install a MySQL apt config package to add the repos.

```bash
sudo apt install -y lsb-release wget
wget https://dev.mysql.com/get/mysql-apt-config_0.8.28-1_all.deb
sudo dpkg -i mysql-apt-config_0.8.28-1_all.deb
```

Then, run

```bash
sudo apt update
sudo apt install mysql-server mysql-client
```

Documentation is [here](https://dev.mysql.com/doc/refman/8.2/en/linux-installation-apt-repo.html#:~:text=1%20Preconfigure%20the%20MySQL%20server%20package%20with%20the,them%20using%20apt-get%20%3A%20sudo%20apt-get%20-f%20install).

Is there any interest in fixing this with a PR?

https://github.com/AlternC/easy-install/blob/25fd51e10c374bbf1384f8b1e1d2afc1cd0cfc53/install.sh#L482

**Comment by camlafit** [comment]
Hi

Actually Debian 11 and 12 are not supported.
You can follow this issue https://github.com/AlternC/AlternC/issues/542

About mysql Debian don't support anymore it but mariadb. To follow this change we can use this transitional package : 
https://packages.debian.org/bookworm/default-mysql-server must change to mariadb-server

**Comment by albancrommer** [comment]
On the long run, I'm not even sure AlternC wants to maintain this install method, which should be an ansible script at best.

But if we do keep the bash install method, this apt dependency will be the first line we'll patch. 

So don't worry about a PR here, it's not that important.

Thanks for the feedback, though!

**Comment by rsmithlal** [comment]
Thanks for the update. I'll follow the development in the main repo as linked above. Cheers, happy holidays, folks!
