### ISSUE TITLE
Ignore local IP if only RFC1918

### ISSUE THREAD

**Issue by camlafit** [AlternC/easy-install#2]
Hi

On https://github.com/AlternC/easy-install/blob/master/lib_installer.sh#L209 if we provide a public IP but server is rooted with RFC1918 IP matching can't be done.

Installation can't be continue

**Comment by albancrommer** [comment]
Fixed 

https://github.com/AlternC/easy-install/commit/6a8948a14eb22fcfbe326d945455545a0ec9b1d1
