### ISSUE TITLE
Roundcube module not installing.

### ISSUE THREAD

**Issue by albancrommer** [AlternC/easy-install#5]
User validates to add the module, it's not included. Sadness ensues.

**Comment by hostquota** [comment]
Sadness indeed, I have the same problem. But it seems no one is answering these posts anymore. I hope it's still active as it looks like a really promising control panel

**Comment by camlafit** [comment]
Hi

After easy install, you can enable alternc-roundcube via apt-get
> apt-get install alternc-rouncube

Is not perfect but should be ok :)

**Comment by albancrommer** [comment]
Geeh. I need a way to be reminded of such open bugs not resolved.

**Comment by albancrommer** [comment]
Fixed now.
