### ISSUE TITLE
Debian Wheezy Fresh Install: apt-get install -y needs --force-yes

### ISSUE THREAD

**Issue by 0xTHMS** [AlternC/easy-install#8]
On Debian wheezy, if you don't have "pwgen" package installed, the easy_install script tries to install it from the repos.
The problem is that, if it fails, it doesn't stop.

I didn't keep the exact error message but -y needs to be used with --force-yes.
I also thing easy_install should stop on such an error.

**Comment by albancrommer** [comment]
Very late on this. Well, indeed, if apt fails, it should break. 

Fixed in #5b85184.
