### ISSUE TITLE
Something wrong with the easy install

### ISSUE THREAD

**Issue by hostquota** [AlternC/easy-install#9]
In the left column, awstats, and server certificates tabs are missing, in fact easy install doesn't download roundcube, awstats or mailman. The download for debian wheezy inckudes all of them, but the version easyinstall downloads has them missing, plus if I try to go through it slowly myself, I get an error saying 'expected wheezy, got jessie'.
Tried doing the manual install by translating the instructions on google translate, very good, but there's a lot missing from those instructions. Too many things missing php being one of them.
This is a real shame because it looks like a promising panel.
I installed awstats manually, but it doesn't show up in the menu, and on my first attempt (I'm now on my third!) when I installed roundcube, i got an error message saying there's an error in your apache conf we will not restart it.
I've downloaded the wheezy version, I just don't know what directory to put it in to attempt installing this myself, can anyone advise me?

**Comment by camlafit** [comment]
Hi

After install a module as alternc-mailman or alternc-roundcube via apt-get.
Have you run alternc.install ?

After an alternc installation, we must run this script alternc.install.
This script apply all changes provided by alternc or module.

**Comment by hostquota** [comment]
Yes, thanks for your answer, I did get it going after all. Alternc is quite simply brilliant. It's lacking a few features and I'm afraid I'm not a developer at that level, but willing to learn. I was wondering why development seems to have stopped on it? To be really honest, I've tried every open source panel out there and there isn't one that I would be happy to provide to customers, as there's always something which is neglaected or over-looked, plus too much development often outdates modules, eg, someone might create an add on for version 1 then suddenly they bring out version 2. But Alternc has inspired me, seriously. It's solid, it seems to be well made, I don't understand why it doesn't seem to have a great developer community? Could you advise on how to create modules for it?

**Comment by camlafit** [comment]
Hi

> Yes, thanks for your answer, I did get it going after all.

It's a workaround, and indeed we must work to evolve this feature on
easy install. Actually we use this script to help ourself in first
step install and we tune our configuration as explained.


> Alternc is quite
> simply brilliant. It's lacking a few features and I'm afraid I'm not a
> developer at that level, but willing to learn. I was wondering why
> development seems to have stopped on it? To be really honest, I've tried
> every open source panel out there and there isn't one that I would be happy
> to provide to customers, as there's always something which is neglaected or
> over-looked, plus too much development often outdates modules, eg, someone
> might create an add on for version 1 then suddenly they bring out version 2.
> But Alternc has inspired me, seriously. It's solid, it seems to be well
> made, I don't understand why it doesn't seem to have a great developer
> community?

thanks :)
We try to work on but we have few time :/ When we have needs we work
on alternc and report these evolves after but to provide this with
quality take time and team is little.
You're welcome to help us as you do actually. You can open suggestion, bug, ...


> Could you advise on how to create modules for it?

If you have specific demand I suggest you to open new issu, should be better.
I suggest you to check other plugin set on our repository. Actually we
an unique repo for all project (core alternc and plugin)
We are also on irc.freenode.net , #alternc channel.

**Comment by hostquota** [comment]
Thanks Camlafit, it's good to meet you, and I will put up some suggestions. I have limited knowledge at server level, but trying my best to understand, I was hoping that maybe there was a sample plug-in, which could be used as a starting point?

**Comment by camlafit** [comment]
Hi

I'm' sorry we don't have a simple plugin or guidelines to extend alternc features. We muse read , read and reread code on https://github.com/AlternC/AlternC/issues ...

We are open to help you on specific quesiton on irc, mailing or with issue. But it's more delicate to give you a global response.

**Comment by albancrommer** [comment]
The roundcube / mailman bug has been fixed. 
Awstat is not currently supported, so I guess we can close the issue.
